vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: '%products_images%'
            upload_destination: '%kernel.project_dir%/public%products_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false 
            delete_on_remove: false
        realisations: 
            uri_prefix: '%realisations_images%'
            upload_destination: '%kernel.project_dir%/public%realisations_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false 
            delete_on_remove: false
