#index:
#    path: /
#    controller: App\Controller\DefaultController::index

paiement_paypal:
    path: '/commande/creer-session-paypal/{reference}'
    controller: App\Controller\PaymentController::paypalCheckout
    methods: ['POST']